# =============================
# Project-Hail-Mary Theme
# =============================

set $bg      #100C0D
set $fg      #E4DEAB
set $border  #D7CF68
set $accent  #7898A2
set $urgent  #D2BE6A
set $gray    #171212

# Window colors
#                       border   background  text    indicator  child_border
client.focused          $border  $border     $fg     $accent    $border
client.focused_inactive $gray    $gray       $fg     $gray      $gray
client.unfocused        $bg      $bg         $fg     $bg        $bg
client.urgent           $urgent  $urgent     $fg     $urgent    $urgent
