# GEANY COLORSCHEME -
# DIGITAL CIRCUS THEME

[theme_info]
name=DIGITAL_CIRCUS
description= The Amazing Digital Circus
version=1.0

[default]
background=#0d0520
foreground=#e7e0f5
caret=#ffffff
selection=#3a23fa
current_line=#1a0f35
line_numbers=#3a23fa
brace_good=#93fb03
brace_bad=#e7244e

[keywords]
primary=#3a23fa
secondary=#07c4d6
type=#93fb03
comment=#3a23fa
string=#93fb03
number=#eb7202

[named_styles]
default=#e7e0f5;#0d0520;false;false
error=#e7244e;#0d0520;false;false
comment=#3a23fa;#0d0520;false;true
comment_doc=#3a23fa;#0d0520;false;false
comment_line=#3a23fa;#0d0520;false;true
comment_line_doc=#3a23fa;#0d0520;false;false
comment_doc_keyword=#07c4d6;#0d0520;true;false
comment_doc_keyword_error=#e7244e;#0d0520;false;false
number=#eb7202;#0d0520;false;false
number_1=#eb7202;#0d0520;false;false
number_2=#eb7202;#0d0520;false;false
type=#93fb03;#0d0520;true;false
class=#93fb03;#0d0520;true;false
function=#07c4d6;#0d0520;false;false
parameter=#e7e0f5;#0d0520;false;true
keyword=#3a23fa;#0d0520;true;false
keyword_1=#3a23fa;#0d0520;true;false
keyword_2=#07c4d6;#0d0520;false;false
keyword_3=#93fb03;#0d0520;false;false
keyword_4=#3a23fa;#0d0520;false;false
identifier=#e7e0f5;#0d0520;false;false
identifier_1=#e7e0f5;#0d0520;false;false
identifier_2=#e7e0f5;#0d0520;false;false
string=#93fb03;#0d0520;false;false
string_1=#93fb03;#0d0520;false;false
string_2=#93fb03;#0d0520;false;false
string_3=#93fb03;#0d0520;false;false
string_4=#93fb03;#0d0520;false;false
string_eol=#e7244e;#0d0520;false;false
character=#93fb03;#0d0520;false;false
backtick=#93fb03;#0d0520;false;false
here_doc=#93fb03;#0d0520;false;false
scalar=#93fb03;#0d0520;false;false
label=#07c4d6;#0d0520;false;true
preprocessor=#3a23fa;#0d0520;false;false
preprocessor_1=#3a23fa;#0d0520;false;false
preprocessor_2=#3a23fa;#0d0520;false;false
regex=#eb7202;#0d0520;false;false
regex_1=#eb7202;#0d0520;false;false
operator=#e7244e;#0d0520;false;false
decorator=#07c4d6;#0d0520;false;false
other=#e7e0f5;#0d0520;false;false
extra=#93fb03;#0d0520;false;false
tag=#3a23fa;#0d0520;true;false
tag_unknown=#e7244e;#0d0520;false;false
tag_end=#3a23fa;#0d0520;false;false
attribute=#07c4d6;#0d0520;false;false
attribute_unknown=#eb7202;#0d0520;false;false
value=#93fb03;#0d0520;false;false
entity=#eb7202;#0d0520;false;false
