# GEANY COLORSCHEME -
# EMBER-MOON THEME

[theme_info]
name=EMBER_MOON
description=Ember Moon Dark
version=1.0

[default]
background=#141417
foreground=#C9CED6
caret=#FFFFFF
selection=#262A33
current_line=#1C1F26
line_numbers=#7E8794

brace_good=#F4B942
brace_bad=#E10600

[keywords]
primary=#FF7AA2
secondary=#FF4D88
type=#F4B942
comment=#7E8794
string=#FF7AA2
number=#F4B942

[named_styles]
default=#C9CED6;#141417;false;false
error=#E10600;#141417;false;false

comment=#7E8794;#141417;false;true
comment_doc=#7E8794;#141417;false;false
comment_line=#7E8794;#141417;false;true
comment_line_doc=#7E8794;#141417;false;false
comment_doc_keyword=#F4B942;#141417;true;false
comment_doc_keyword_error=#E10600;#141417;false;false

number=#F4B942;#141417;false;false
number_1=#F4B942;#141417;false;false
number_2=#F4B942;#141417;false;false

type=#F4B942;#141417;true;false
class=#F4B942;#141417;true;false

function=#FF4D88;#141417;false;false
parameter=#C9CED6;#141417;false;true

keyword=#FF7AA2;#141417;true;false
keyword_1=#FF7AA2;#141417;true;false
keyword_2=#FF4D88;#141417;false;false
keyword_3=#F4B942;#141417;false;false
keyword_4=#FF7AA2;#141417;false;false

identifier=#C9CED6;#141417;false;false
identifier_1=#C9CED6;#141417;false;false
identifier_2=#C9CED6;#141417;false;false

string=#FF7AA2;#141417;false;false
string_1=#FF7AA2;#141417;false;false
string_2=#FF7AA2;#141417;false;false
string_3=#FF7AA2;#141417;false;false
string_4=#FF7AA2;#141417;false;false
string_eol=#E10600;#141417;false;false

character=#FF7AA2;#141417;false;false
backtick=#FF7AA2;#141417;false;false
here_doc=#FF7AA2;#141417;false;false
scalar=#FF7AA2;#141417;false;false

label=#FF4D88;#141417;false;true

preprocessor=#F4B942;#141417;false;false
preprocessor_1=#F4B942;#141417;false;false
preprocessor_2=#F4B942;#141417;false;false

regex=#F4B942;#141417;false;false
regex_1=#F4B942;#141417;false;false

operator=#C9CED6;#141417;false;false
decorator=#FF4D88;#141417;false;false

other=#C9CED6;#141417;false;false
extra=#F4B942;#141417;false;false

tag=#FF7AA2;#141417;true;false
tag_unknown=#E10600;#141417;false;false
tag_end=#FF7AA2;#141417;false;false

attribute=#FF4D88;#141417;false;false
attribute_unknown=#F4B942;#141417;false;false

value=#FF7AA2;#141417;false;false
entity=#F4B942;#141417;false;false
