# GEANY COLORSCHEME -
# DRACULA THEME

[theme_info]
name=Hexd-Dracula
description=Dracula 
version=1.0

[default]
background=#282A36
foreground=#F8F8F2
caret=#F8F8F2
selection=#44475A
current_line=#303241
line_numbers=#6272A4
 
brace_good=#50FA7B
brace_bad=#FF5555

[keywords]
primary=#BD93F9
secondary=#8BE9FD
type=#FFB86C
comment=#6272A4
string=#F1FA8C
number=#FF79C6

[named_styles]
default=#F8F8F2;#282A36;false;false
error=#FF5555;#282A36;false;false

comment=#6272A4;#282A36;false;true
comment_doc=#6272A4;#282A36;false;false
comment_line=#6272A4;#282A36;false;true
comment_line_doc=#6272A4;#282A36;false;false
comment_doc_keyword=#8BE9FD;#282A36;true;false
comment_doc_keyword_error=#FF5555;#282A36;false;false

number=#FF79C6;#282A36;false;false
number_1=#FF79C6;#282A36;false;false
number_2=#FF79C6;#282A36;false;false

type=#FFB86C;#282A36;true;false
class=#FFB86C;#282A36;true;false

function=#8BE9FD;#282A36;false;false
parameter=#F8F8F2;#282A36;false;true

keyword=#BD93F9;#282A36;true;false
keyword_1=#BD93F9;#282A36;true;false
keyword_2=#8BE9FD;#282A36;false;false
keyword_3=#FFB86C;#282A36;false;false
keyword_4=#BD93F9;#282A36;false;false

identifier=#F8F8F2;#282A36;false;false
identifier_1=#F8F8F2;#282A36;false;false
identifier_2=#F8F8F2;#282A36;false;false

string=#F1FA8C;#282A36;false;false
string_1=#F1FA8C;#282A36;false;false
string_2=#F1FA8C;#282A36;false;false
string_3=#F1FA8C;#282A36;false;false
string_4=#F1FA8C;#282A36;false;false
string_eol=#FF5555;#282A36;false;false

character=#F1FA8C;#282A36;false;false
backtick=#F1FA8C;#282A36;false;false
here_doc=#F1FA8C;#282A36;false;false
scalar=#F1FA8C;#282A36;false;false

label=#FF79C6;#282A36;false;true

preprocessor=#FFB86C;#282A36;false;false
preprocessor_1=#FFB86C;#282A36;false;false
preprocessor_2=#FFB86C;#282A36;false;false

regex=#FF79C6;#282A36;false;false
regex_1=#FF79C6;#282A36;false;false

operator=#F8F8F2;#282A36;false;false
decorator=#8BE9FD;#282A36;false;false

other=#F8F8F2;#282A36;false;false
extra=#BD93F9;#282A36;false;false

tag=#BD93F9;#282A36;true;false
tag_unknown=#FF5555;#282A36;false;false
tag_end=#BD93F9;#282A36;false;false

attribute=#8BE9FD;#282A36;false;false
attribute_unknown=#FF79C6;#282A36;false;false

value=#F1FA8C;#282A36;false;false
entity=#FF79C6;#282A36;false;false
