# GEANY COLORSCHEME -
# NEON-VIOLET THEME

[theme_info]
name=NEON_VIOLET
description=Neon Violet (glassy purple + pink accents)
version=1.0

[default]
background=#1F1F27
foreground=#F8F2FF
caret=#E741BB
selection=#451B7E
current_line=#2A2234
line_numbers=#A98DB8

brace_good=#7D3CBE
brace_bad=#C43799

[keywords]
primary=#E741BB
secondary=#7D3CBE
type=#EDB4DD
comment=#A98DB8
string=#EDB4DD
number=#C77DFF

[named_styles]
default=#F8F2FF;#1F1F27;false;false
error=#C43799;#1F1F27;false;false

comment=#A98DB8;#1F1F27;false;true
comment_doc=#A98DB8;#1F1F27;false;false
comment_line=#A98DB8;#1F1F27;false;true
comment_line_doc=#A98DB8;#1F1F27;false;false
comment_doc_keyword=#7D3CBE;#1F1F27;true;false
comment_doc_keyword_error=#C43799;#1F1F27;false;false

number=#C77DFF;#1F1F27;false;false
number_1=#C77DFF;#1F1F27;false;false
number_2=#C77DFF;#1F1F27;false;false

type=#EDB4DD;#1F1F27;true;false
class=#EDB4DD;#1F1F27;true;false

function=#7D3CBE;#1F1F27;false;false
parameter=#F8F2FF;#1F1F27;false;true

keyword=#E741BB;#1F1F27;true;false
keyword_1=#E741BB;#1F1F27;true;false
keyword_2=#7D3CBE;#1F1F27;false;false
keyword_3=#EDB4DD;#1F1F27;false;false
keyword_4=#E741BB;#1F1F27;false;false

identifier=#F8F2FF;#1F1F27;false;false
identifier_1=#F8F2FF;#1F1F27;false;false
identifier_2=#F8F2FF;#1F1F27;false;false

string=#EDB4DD;#1F1F27;false;false
string_1=#EDB4DD;#1F1F27;false;false
string_2=#EDB4DD;#1F1F27;false;false
string_3=#EDB4DD;#1F1F27;false;false
string_4=#EDB4DD;#1F1F27;false;false
string_eol=#C43799;#1F1F27;false;false

character=#EDB4DD;#1F1F27;false;false
backtick=#EDB4DD;#1F1F27;false;false
here_doc=#EDB4DD;#1F1F27;false;false
scalar=#EDB4DD;#1F1F27;false;false

label=#E741BB;#1F1F27;false;true

preprocessor=#7D3CBE;#1F1F27;false;false
preprocessor_1=#7D3CBE;#1F1F27;false;false
preprocessor_2=#7D3CBE;#1F1F27;false;false

regex=#C77DFF;#1F1F27;false;false
regex_1=#C77DFF;#1F1F27;false;false

operator=#F8F2FF;#1F1F27;false;false
decorator=#7D3CBE;#1F1F27;false;false

other=#F8F2FF;#1F1F27;false;false
extra=#EDB4DD;#1F1F27;false;false

tag=#E741BB;#1F1F27;true;false
tag_unknown=#C43799;#1F1F27;false;false
tag_end=#E741BB;#1F1F27;false;false

attribute=#7D3CBE;#1F1F27;false;false
attribute_unknown=#C77DFF;#1F1F27;false;false

value=#EDB4DD;#1F1F27;false;false
entity=#C77DFF;#1F1F27;false;false
