# GEANY COLORSCHEME -
# NORD THEME

[theme_info]
name=NORD_THEME
description=Nord Dark
version=1.0

[default]
background=#2E3440
foreground=#D8DEE9
caret=#ECEFF4
selection=#4C566A
current_line=#3B4252
line_numbers=#616E88

brace_good=#A3BE8C
brace_bad=#BF616A

[keywords]
primary=#81A1C1
secondary=#88C0D0
type=#8FBCBB
comment=#616E88
string=#A3BE8C
number=#B48EAD

[named_styles]
default=#D8DEE9;#2E3440;false;false
error=#BF616A;#2E3440;false;false

comment=#616E88;#2E3440;false;true
comment_doc=#616E88;#2E3440;false;false
comment_line=#616E88;#2E3440;false;true
comment_line_doc=#616E88;#2E3440;false;false
comment_doc_keyword=#88C0D0;#2E3440;true;false
comment_doc_keyword_error=#BF616A;#2E3440;false;false

number=#B48EAD;#2E3440;false;false
number_1=#B48EAD;#2E3440;false;false
number_2=#B48EAD;#2E3440;false;false

type=#8FBCBB;#2E3440;true;false
class=#8FBCBB;#2E3440;true;false

function=#88C0D0;#2E3440;false;false
parameter=#D8DEE9;#2E3440;false;true

keyword=#81A1C1;#2E3440;true;false
keyword_1=#81A1C1;#2E3440;true;false
keyword_2=#88C0D0;#2E3440;false;false
keyword_3=#8FBCBB;#2E3440;false;false
keyword_4=#81A1C1;#2E3440;false;false

identifier=#D8DEE9;#2E3440;false;false
identifier_1=#D8DEE9;#2E3440;false;false
identifier_2=#D8DEE9;#2E3440;false;false

string=#A3BE8C;#2E3440;false;false
string_1=#A3BE8C;#2E3440;false;false
string_2=#A3BE8C;#2E3440;false;false
string_3=#A3BE8C;#2E3440;false;false
string_4=#A3BE8C;#2E3440;false;false
string_eol=#BF616A;#2E3440;false;false

character=#A3BE8C;#2E3440;false;false
backtick=#A3BE8C;#2E3440;false;false
here_doc=#A3BE8C;#2E3440;false;false
scalar=#A3BE8C;#2E3440;false;false

label=#88C0D0;#2E3440;false;true

preprocessor=#81A1C1;#2E3440;false;false
preprocessor_1=#81A1C1;#2E3440;false;false
preprocessor_2=#81A1C1;#2E3440;false;false

regex=#B48EAD;#2E3440;false;false
regex_1=#B48EAD;#2E3440;false;false

operator=#D8DEE9;#2E3440;false;false
decorator=#88C0D0;#2E3440;false;false

other=#D8DEE9;#2E3440;false;false
extra=#8FBCBB;#2E3440;false;false

tag=#81A1C1;#2E3440;true;false
tag_unknown=#BF616A;#2E3440;false;false
tag_end=#81A1C1;#2E3440;false;false

attribute=#88C0D0;#2E3440;false;false
attribute_unknown=#B48EAD;#2E3440;false;false

value=#A3BE8C;#2E3440;false;false
entity=#B48EAD;#2E3440;false;false
