print_info() {
    info title

    # Blood red for the outline only
    local YL="$(color 1)"
    local RS="$(color 1)"

    prin "${YL}┌──────────── ${RS}$(color 3)Software${YL} ────────────${RS}"
    info "${YL}│${RS} $(color 1) OS " distro
    info "${YL}│${RS} $(color 1) KER" kernel
    info "${YL}│${RS} $(color 3) PKG" packages
    info "${YL}│${RS} $(color 3) SHL" shell
    info "${YL}│${RS} $(color 3) TER" term
    info "${YL}│${RS} $(color 3) WM " wm
    info "${YL}│${RS} $(color 7) SNG" song
    prin "${YL}├──────────── ${RS}$(color 3)Hardware${YL} ────────────${RS}"
    info "${YL}│${RS} $(color 2) UPT" uptime
    info "${YL}│${RS} $(color 5) HST" model
    info "${YL}│${RS} $(color 3) CPU" cpu
    info "${YL}│${RS} $(color 3) GPU" gpu
    info "${YL}│${RS} $(color 5) MEM" memory
    prin "${YL}└──────── ${RS}$(color 0)󰝤 $(color 1)󰝤 $(color 2)󰝤 $(color 3)󰝤 $(color 4)󰝤 $(color 5)󰝤 $(color 6)󰝤 $(color 7)󰝤 ${YL}─────────${RS}"

    prin "$(color 7)　　　　　　　　　　　I $(color 1)󰋑 $(color 7)Archcraft"

    info cols
}


##--------- Title
title_fqdn="off"


##--------- Kernel
kernel_shorthand="off"


##--------- Distro
distro_shorthand="off"
os_arch="on"


##--------- Uptime
uptime_shorthand="on"


##--------- Memory
memory_percent="off"
memory_unit="gib"


##--------- Packages
package_managers="on"


##--------- Shell
shell_path="off"
shell_version="on"


##--------- CPU
speed_type="bios_limit"
speed_shorthand="on"
cpu_brand="on"
cpu_speed="on"
cpu_cores="off"
cpu_temp="off"


##--------- GPU
gpu_brand="on"
gpu_type="all"


##--------- Resolution
refresh_rate="on"


##--------- Gtk Theme / Icons / Font
gtk_shorthand="off"
gtk2="on"
gtk3="on"


##--------- IP Address
public_ip_host="http://ident.me"
public_ip_timeout=2
de_version="on"


##--------- Disk
disk_show=('/')
disk_subtitle="mount"
disk_percent="on"


##--------- Song
music_player="auto"
song_format="%artist% - %title%"
song_shorthand="off"
mpc_args=()


##--------- Text Colors
# order: 'title', '@', 'underline', 'subtitle', 'colon', 'info'
# 1=red, 3=yellow/amber, 7=white
colors=(1 7 1 7 1 7)


##--------- Text Options
bold="on"
underline_enabled="on"
underline_char="-"
separator=" 🢒"


##--------- Color Blocks
block_range=(0 15)
color_blocks="off"
block_width=3
block_height=1
col_offset="auto"


##--------- Progress Bars
bar_char_elapsed="█"
bar_char_total="░"
bar_border="off"
bar_length=15
bar_color_elapsed="1"
bar_color_total="3"
cpu_display="off"
memory_display="off"
battery_display="off"
disk_display="off"


##--------- Backend Settings
image_backend="kitty"
image_source="$HOME/.config/neofetch/images/ena.png"


##--------- Ascii Options
ascii_distro="auto"
ascii_colors=(1 1 1 1 1 1)
ascii_bold="on"


##--------- Image Options
image_loop="off"
thumbnail_dir="${XDG_CACHE_HOME:-${HOME}/.cache}/thumbnails/neofetch"
crop_mode="normal"
crop_offset="center"
image_size="300px"
# try 220px–320px

gap=2
yoffset=0
xoffset=0
background_color=


##--------- Misc Options
stdout="off"
