# =============================
# Blue-Yellow Theme
# =============================

set $bg      #123d88
set $fg      #EAF6FF
set $border  #FFD36A
set $accent  #33D6FF
set $urgent  #FF5B6E
set $gray    #1E6FA6

# Window colors
#                       border   background  text    indicator  child_border
client.focused          $border  $bg         $fg     $accent    $border
client.focused_inactive $gray    $bg         $fg     $gray      $gray
client.unfocused        $bg      $bg         $fg     $bg        $bg
client.urgent           $urgent  $urgent     $fg     $urgent    $urgent
