# ==============================
# EMBER MOON
# ==============================

# Base colors
set $bg         #141417
set $bg-alt     #1C1F26
set $fg         #C9CED6

# Accents
set $accent     #FF4D88
set $accent-alt #FF7AA2
set $gold       #F4B942
set $red        #E10600

# ------------------------------
# Window borders
# ------------------------------

# class                 border   background  text      indicator  child_border

client.focused          $accent  $accent     #000000   $gold      $accent
client.focused_inactive $bg-alt  $bg-alt     $fg       $accent-alt $bg-alt
client.unfocused        $bg      $bg         $fg       $bg        $bg
client.urgent           $red     $red        #ffffff   $gold      $red
