; Arch Rain 

[colors]
background     = #151E26
background-alt = #1C2832
foreground     = #E6F0F5
primary        = #0460b3
secondary      = #04548b
accent         = #7FF7FF
border         = #2B3B48
muted          = #2B5163
disabled       = #2B3B48
warn           = #FF7A7A
alert          = #D06060
time           = #FFFFFF
theme          = #10E8FF
ttbar          = #151E26
circle         = #7FF7FF
msc            = #25c8ff
star           = #D09050
updates        = #25C8FF
title          = #FFFFFF
pacman         = #10E8FF

;theme - theme icon
;ttbar - top toolbar on right
;circle - rofi app launcher button
;msc - music buttons
;star - eww sidebar launcher button
;updates - pacman icon
;title = music title
;pacman - pacman icon
