; Black Rock Shooter

[colors]
background     = #0a0e17
background-alt = #152033
foreground     = #cce0f0
primary        = #1a4a7a
secondary      = #00c8d4
accent         = #00c8d4
border         = #152033
muted          = #2a4a6a
warn           = #1e88e5
alert          = #1e88e5
disabled       = #2a4a6a
time           = #ffffff
theme          = #00C8D4
ttbar          = #00C8D4
msc            = #0a0e17
star           = #00c8d4
updates        = #ffffff
title          = #ffffff
pacman         = #00c8d4

;theme - theme icon
;ttbar - top toolbar on right
;circle - rofi app launcher button
;msc - music buttons
;star - eww sidebar launcher button
;updates - pacman icon
;title = music title
;pacman - pacman icon


