; Celty

[colors]
background     = #0d0d0d
background-alt = #1a1a1a
foreground     = #f0f0f0
primary        = #888888
secondary      = #c8c8c8
accent         = #c8c8c8
border         = #1a1a1a
muted          = #555555
warn           = #ffffff
alert          = #ffffff
disabled       = #444444
time           = #ffffff
theme          = #c8c8c8
ttbar          = #0d0d0d
circle         = #ffffff
msc            = #888888
star           = #ffffff
updates        = #ffffff
title          = #0d0d0d
pacman         = #0d0d0d

;theme - theme icon
;ttbar - top toolbar on right
;circle - rofi app launcher button
;msc - music buttons
;star - eww sidebar launcher button
;updates - pacman icon
;title = music title
;pacman - pacman icon
