; Chill

[colors]
background     = #0c0f24
background-alt = #19243a
foreground     = #e7ecf5
primary        = #19243a
secondary      = #4a5c68
accent         = #78b7c8
border         = #233647
muted          = #9aa5b8
warn           = #b86a6a
alert          = #b86a6a
disabled       = #7f8aa0
time           = #ffffff
theme          = #daa16c
ttbar          = #daa16c
circle         = #daa16c
msc            = #daa16c
star           = #daa16c
updates        = #ffffff
title          = #ffffff
pacman         = #daa16c

;theme - theme icon
;ttbar - top toolbar on right
;circle - rofi app launcher button
;msc - music buttons
;star - eww sidebar launcher button
;updates - pacman icon
;title = music title
;pacman - pacman icon
