; Dracula

[colors]
background     = #282a36
background-alt = #44475a
foreground     = #f8f8f2
primary        = #bd93f9
secondary      = #ff79c6
accent         = #8be9fd
border         = #44475a
muted          = #6272a4
warn           = #ff5555
alert          = #ff5555
disabled       = #6272a4
time           = #282a36
ttbar          = #282a36
circle         = #ff79c6
msc            = #ffffff
star           = #bd93f9
updates        = #ffffff
title          = #282a36
pacman         = #282a36

;theme - theme icon
;ttbar - top toolbar on right
;circle - rofi app launcher button
;msc - music buttons
;star - eww sidebar launcher button
;updates - pacman icon
;title = music title
;pacman - pacman icon
