; Neon - Violet 

[colors]
background     = #201028
background-alt = #341745
foreground     = #f8f2ff
primary        = #e741bb
secondary      = #7d3cbe
accent         = #e741bb
border         = #602da4
muted          = #4a3456
warn           = #c43799
alert          = #c43799
disabled       = #4a3456
time           = #f8f2ff
theme          = #201028
ttbar          = #201028
circle         = #edb4dd
msc            = #201028
star           = #edb4dd
updates        = #ffffff
title          = #201028
pacman         = #201028

;theme - theme icon
;ttbar - top toolbar on right
;circle - rofi app launcher button
;msc - music buttons
;star - eww sidebar launcher button
;updates - pacman icon
;title = music title
;pacman - pacman icon
