; Nord

[colors]
background     = #2e3440
background-alt = #3b4252
foreground     = #eceff4
primary        = #5e81ac
secondary      = #88c0d0
accent         = #88c0d0
border         = #3b4252
muted          = #4c566a
warn           = #bf616a
alert          = #bf616a
disabled       = #4c566a
time           = #ffffff
theme          = #88C0D0
ttbar          = #2e3440
circle         = #ffffff
msc            = #5e81ac
star           = #ffffff
updates        = #ffffff
title          = #2e3440
pacman         = #2e3440

;theme - theme icon
;ttbar - top toolbar on right
;circle - rofi app launcher button
;msc - music buttons
;star - eww sidebar launcher button
;updates - pacman icon
;title = music title
;pacman - pacman icon

