[colors]
background     = #1a0f1a
background-alt = #2a1e2a
foreground     = #f0e6ec
primary        = #5a8ab0
secondary      = #e8a0c0
accent         = #e8a0c0
border         = #2a1e2a
muted          = #3d2a3d
warn           = #c85a5a
alert          = #c85a5a
disabled       = #3d2a3d
time           = #f0e6ec
theme          = #f0e6ec
ttbar          = #1a0f1a
circle         = #f0e6ec
msc            = #5a8ab0
star           = #f0e6ec
updates        = #ffffff
title          = #1a0f1a
pacman         = #1a0f1a

;theme - theme icon
;ttbar - top toolbar on right
;circle - rofi app launcher button
;msc - music buttons
;star - eww sidebar launcher button
;updates - pacman icon
;title = music title
;pacman - pacman icon
