# i3 theme: chill

# Window borders
client.focused          #DB9B67 #0B0D23 #CBD4E2 #DB9B67 #DB9B67
client.focused_inactive #293246 #0B0D23 #93A0B4 #293246 #293246
client.unfocused        #1C2236 #0B0D23 #6E7C93 #1C2236 #1C2236
client.urgent           #B86A6A #0B0D23 #FFE9D8 #B86A6A #B86A6A
client.placeholder      #1C2236 #0B0D23 #6E7C93 #1C2236 #1C2236

# Optional niceness
default_border pixel 2
default_floating_border pixel 2
