# =============================
# Dracula Theme
# =============================

set $bg      #282a36
set $fg      #f8f8f2
set $border  #bd93f9
set $accent  #ff79c6
set $urgent  #ff5555
set $gray    #44475a

# Window colors
#                       border   background  text    indicator  child_border
client.focused          $border  $border     $fg     $accent    $border
client.focused_inactive $gray    $gray       $fg     $gray      $gray
client.unfocused        $bg      $bg         $fg     $bg        $bg
client.urgent           $urgent  $urgent     $fg     $urgent    $urgent
