# Chill
background            #0c0f24
foreground            #e7ecf5
selection_background  #19243a
selection_foreground  #e7ecf5
cursor                #bb865e
cursor_text_color     #0c0f24
# Black
color0  #0a0c1d
color8  #4d4d55

# Red
color1  #b86a6a
color9  #d18888

# Green
color2  #6fa38e
color10 #8ac0aa
# Yellow (warm candle)
color3  #daa16c
color11 #f0c68f

# Blue
color4  #2d4a6e
color12 #3a5c86

# Magenta
color5  #7c6da8
color13 #9a8ccc
# Cyan
color6  #78b7c8
color14 #9fd6e2

# White
color7  #cbd4e2
color15 #ffffff

background_opacity 0.92
