background            #0b0000
foreground            #f5f5f5
selection_background  #140000
selection_foreground  #f5f5f5
cursor                #ff1a1a
cursor_text_color     #0b0000

color0  #140000
color8  #300000

color1  #ff1a1a
color9  #ff1a1a

color2  #b00000
color10 #b00000

color3  #ff4040
color11 #ff4040

color4  #b00000
color12 #b00000

color5  #ff1a1a
color13 #ff1a1a

color6  #ff6666
color14 #ff6666

color7  #e0e0e0
color15 #ffffff

background_opacity 0.95
