# Purple Plastic
background            #5B4FE8
foreground            #39FF6E
selection_background  #7B6FF0
selection_foreground  #1A1733
cursor                #39FF6E
cursor_text_color     #1A1733

# Black
color0  #1A1733
color8  #2E2660

# Red
color1  #A03060
color9  #C03878

# Green
color2  #39FF6E
color10 #5CFFA0

# Yellow
color3  #B8FF45
color11 #D4FF80

# Blue
color4  #4840C7
color12 #7B6FF0

# Magenta
color5  #8A3FE8
color13 #B06FFF

# Cyan
color6  #5B4FE8
color14 #7B6FF0

# White
color7  #C8BEFF
color15 #EDE9FF

background_opacity 0.92
