;========================
; IMPORT THEME FILE
;========================
include-file = ~/.config/polybar/themes/current_theme.ini
 
    
;========================
;========================
;  TOP BAR 
;========================
;========================
[bar/top]
monitor = ${env:MONITOR:eDP1}
monitor-fallback = eDP1

dpi = 80
monitor-strict = false
width = 100%
offset-x = 0
height = 30
fixed-center = true

background = ${colors.background}
#foreground = ${colors.fg}

border-size = 0
border-bottom-size = 2
border-bottom-color = ${colors.secondary}
border-color = ${colors.border}

line-size = 0
line-color = ${colors.accent}

padding-left = 1
padding-right = 1
module-margin = 0

override-redirect = false
wm-restack = i3

enable-ipc = true

font-0 = JetBrains Mono:size=12;2
font-1 = JetBrainsMono Nerd Font Mono:size=12;2
font-2 = JetBrainsMono Nerd Font Mono:size=17;3
font-3 = JetBrainsMono Nerd Font Mono:size=18;2
font-4 = Noto Color Emoji:size=12;2
font-5 = JetBrainsMono Nerd Font Mono:size=20;2
font-6 = JetBrainsMono Nerd Font Mono:size=24;2

;========================
; TOP BAR
; MODULES - BE CAREFUL MOVING AND REMOVING. 
; EWW MODULES ARE HARD CODED TO CERTAIN AREAS 
; MAKE SURE TO CHANGE THEIR LOCATION IF YOU WISH
; TO MOVE MODULES.
;
; EWW = SIDEBAR, BT, WIFI, BRIGHTNESS, AND VOLSCALE.
;========================

modules-left   = sidebar sep i3 sep
modules-center = sep weather sep 
modules-right  = esep bt wifi brightness esep battery esep


;========================
;========================
;  BOTTOM BAR 
;========================
;========================
[bar/bottom]
monitor = ${env:MONITOR:eDP1}
monitor-fallback = eDP1

dpi = 80
monitor-strict = false
bottom = true
width = 100%Z
offset-x = 0
height = 32
fixed-center = true

background = ${colors.background}
#foreground = ${colors.fg}

border-size = 0
border-top-size = 2
border-top-color = ${colors.secondary}
border-color = ${colors.border}

line-size = 0
line-color = ${colors.accent}

padding-left = 1
padding-right = 1
module-margin = 0

override-redirect = false
enable-ipc = true

font-0 = JetBrains Mono:size=10;2
font-1 = JetBrainsMono Nerd Font Mono:size=14;2
font-2 = JetBrainsMono Nerd Font Mono:size=13;3
font-3 = JetBrainsMono Nerd Font Mono:size=20;2
font-4 = JetBrains Mono:size=24;2
font-5 = JetBrainsMono Nerd Font Mono:size=26;4

;========================
; MODULES - BE CAREFUL MOVING AND REMOVING. 
; EWW MODULES ARE HARD CODED TO CERTAIN AREAS 
; MAKE SURE TO CHANGE THEIR LOCATION IF YOU WISH
; TO MOVE MODULES.
;
; EWW = SIDEBAR, BT, WIFI, BRIGHTNESS, AND VOLSCALE.
;========================

modules-left   = arch sep mem cpu sep theme
modules-center = sep time12 updates sep
modules-right  = sep volscale pill_start_bottom music_controls music_title pill_end_bottom


;========================
;========================
; 󰞱 Separator 󰞱
;========================
;========================
[module/lsep]
type = custom/text
format = ""
format-foreground = ${colors.border}
format-padding = 1

[module/rsep]
type = custom/text
format = ""
format-foreground = ${colors.border}
format-padding = 1

[module/sep]
type = custom/text
format = ""
format-foreground = ${colors.secondary}
format-padding = 1

;; Light blue spacer
[module/esep]
type = custom/text
format = " "
format-background = ${colors.primary}

;========================
;========================
; 󰐂 Pill wrappers 󰐂
;========================
;========================
[module/pill_start_bottom]
type = custom/text
format = ""
format-background = ${colors.primary}
format-padding = 4

[module/pill_end_bottom]
type = custom/text
format = ""
format-background = ${colors.primary}
format-padding = 4

;========================
;========================
;  Workspaces 
;========================
;========================
[module/i3]
type = internal/i3
pin-workspaces = false
strip-wsnumbers = false
index-sort = true
enable-click = true
enable-scroll = true

format = <label-state>

label-focused = %index%
label-focused-foreground = ${colors.background}
label-focused-background = ${colors.secondary}
label-focused-padding = 2

label-unfocused = %index%
label-unfocused-foreground = ${colors.muted}
label-unfocused-padding = 2

label-visible = %index%
label-visible-foreground = ${colors.foreground}
label-visible-padding = 2

label-urgent = %index%
label-urgent-foreground = ${colors.warn}
label-urgent-background = ${colors.primary}
label-urgent-padding = 2


;========================
;========================
; 󰕳 MODULES 󰕳
;========================
;========================


;========================
; 󰂯 Bluetooth - Eww 󰂯
;========================
[module/bt]
type = custom/text
label = "󰂯"
label-padding = 2
click-left = ~/.config/eww/scripts/menu-toggle.sh bluetooth
label-foreground = ${colors.ttbar}
label-background = ${colors.primary}
label-font = 3

;========================
;  Wifi - Eww 
;========================
[module/wifi]
type = custom/text
label = "󰖩"
label-padding = 2
click-left = ~/.config/eww/scripts/menu-toggle.sh wifi
label-foreground = ${colors.ttbar}
label-background = ${colors.primary}
label-font = 4

;========================
; 󰖐 Weather 󰖐
;========================
[module/weather]
type = custom/script
exec = ~/.config/polybar/scripts/weather-poly.sh
interval = 300
format = <label>
label = %output%
label-background = ${colors.primary}
label-foreground = ${colors.time}
label-padding = 1
label-maxlen = 60
label-ellipsis = false

;========================
;  Time - Month Day - 12 hour 
;========================
[module/time12]
type = internal/date
interval = 1
time = %a %b %d    %I:%M %p
label = %time%
label-background = ${colors.primary}
label-foreground = ${colors.time}
label-padding = 4
label-font = 3

;========================
; 󰍛 Memory 󰍛
;========================
[module/mem]
type = internal/memory
interval = 2
format = <label>
label = "󰘚 %percentage_used%%"
label-foreground = ${colors.foreground}
label-background = ${colors.background}
label-padding = 1
label-font = 1

;========================
;  CPU 
;========================
[module/cpu]
type = internal/cpu
interval = 2
format = <label>
label = "󰍛 %percentage%%"
label-foreground = ${colors.foreground}
label-background = ${colors.background}
label-padding = 1
label-font = 1

;========================
;  Battery 
;========================
[module/battery]
type = custom/script
exec = ~/.config/polybar/scripts/battery.sh
interval = 5
click-left = kitty -e sh -lc 'upower -e && echo && upower -i $(upower -e | grep -m1 BAT)'
click-right = kitty -e sh -lc 'acpi -b || upower -i $(upower -e | grep -m1 BAT)'
format = <label>
label = %output%
label-background = ${colors.primary}
label-foreground = ${colors.ttbar}
label-padding = 2
label-font = 1

;========================
;  App Launcher - Rofi 
;========================
[module/arch]
type = custom/script
exec = ~/.config/polybar/scripts/rofi-toggle.sh
tail = true
click-left = bash ~/.config/rofi/launch-app.sh
label-foreground = ${colors.circle}
label-padding = 1
label-font = 6

;========================
;  Sidebar - Eww 
;========================
[module/sidebar]
type = custom/script
exec = ~/.config/polybar/scripts/eww-sidebar-state.sh sidebar
tail = true
click-left = sh -lc '~/.config/polybar/scripts/eww-toggle-sidebar.sh'
label-font = 7
label-padding = 2
label-foreground = ${colors.star}

;========================
; 󰮯 Pacman Updates 󰮯
;========================
[module/updates]
type = custom/script
exec = checkupdates 2>/dev/null | wc -l
interval = 600
format-prefix = " 󰮯 "
format-prefix-foreground = ${colors.pacman}
format-prefix-background = ${colors.primary}
label = %output%
label-background = ${colors.primary}
label-foreground = ${colors.updates}
label-padding = 2
click-left = kitty -e sudo pacman -Syu
label-font = 1

;========================
;   Theme Picker 
;========================

[module/theme]
type = custom/text
format = ""
format-padding = 1
click-left = bash -lc '~/.config/i3/switch-theme.sh'
format-foreground = ${colors.theme}
format-background = ${colors.primary}
format-font = 4

;========================
; 󰝚 Music 󰝚
;========================
[module/music_controls]
type = custom/text
content = "󰒮  󰐊  󰒭"
content-font = 2
content-foreground = ${colors.msc}
content-background = ${colors.secondary}
content-padding = 2
click-left = playerctl previous
click-middle = playerctl play-pause
click-right = playerctl next

;========================
; 󰝚 Music Title 󰝚
;========================
[module/music_title]
type = custom/script
exec = ~/.config/polybar/scripts/music-title.sh
interval = 1
tail = true
format = <label>
label = %output%
label-background = ${colors.primary}
label-foreground = ${colors.title}
label-padding = 2

;========================
;  Brightness 
;========================
[module/brightness]
type = custom/script
exec = ~/.config/polybar/scripts/brightness-icon.sh
interval = 1

click-left = ~/.config/eww/scripts/menu-toggle.sh brightness

click-right = brightnessctl set 100% 2>/dev/null || xbacklight -set 100
click-middle = brightnessctl set 50% 2>/dev/null || xbacklight -set 50

format = <label>
label = %output%
label-font = 6
label-foreground = ${colors.ttbar}
label-background = ${colors.primary}
label-padding = 2

;========================
;  Volume - EWW 
;========================
[module/volscale]
type = custom/script
exec = ~/.config/polybar/scripts/volume-icon.sh
interval = 1

click-left = ~/.config/eww/scripts/menu-toggle.sh volume

click-right = pavucontrol
click-middle = pactl set-sink-mute @DEFAULT_SINK@ toggle

label = %output%
label-font = 3
label-foreground = ${colors.foreground}
label-background = ${colors.primary}
label-padding = 3

;========================
;========================
;  SETTINGS 
;========================
;========================
[settings]
screenchange-reload = true
pseudo-transparency = false
