# STARSHIP - THEMES
# DRACULA THEME
# https://starship.rs/config/

add_newline = false

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$character
"""

[directory]
style = "bold #BD93F9"						# pale purple / blue

[git_branch]
symbol = '🌱 '
style = "bold #FF79C6"						# bright magenta / pink

[git_status]
style = "#FF5555"							# pale bright red

[username]
style_user = "bold #50FA7B"					# neon green
style_root = "bold #FF5555"					# pale bright red
format = ' [$user]($style) '
disabled = false
show_always = true

[hostname]
style = "#8BE9FD"

[character]
success_symbol = "[❯](bold #BD93F9)"		# pale purple / blue
error_symbol = "[✗](bold red)"
