# =============================
# Devilman Theme
# =============================

set $bg      #0b0000
set $bg-alt  #140000
set $fg      #f5f5f5
set $red     #ff1a1a
set $darkred #b00000
set $muted   #6a0000

#                       border   background  text    indicator  child_border
client.focused          $red     $bg         $fg     $red       $red
client.focused_inactive $darkred $bg-alt     $fg     $darkred   $darkred
client.unfocused        $bg      $bg         $muted  $bg        $bg
client.urgent           $red     $red        $fg     $red       $red
